#!/bin/bash
# User Profile Enhancement - Manual Testing Guide
# This script provides a checklist for manually testing the new user profile features

echo "=================================================="
echo "  User Profile Enhancement - Testing Guide"
echo "=================================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 Prerequisites:${NC}"
echo "  • Expo app running on device/simulator"
echo "  • At least 2 test users in the database"
echo "  • Some bounties posted by different users"
echo ""

echo -e "${BLUE}🧪 Test Scenarios:${NC}"
echo ""

echo -e "${YELLOW}1. Navigation from Bounty Detail Modal${NC}"
echo "   [ ] Open a bounty from the main feed"
echo "   [ ] Tap on the poster's avatar in the detail modal"
echo "   [ ] Verify navigation to user profile screen"
echo "   [ ] Verify back button returns to bounty detail"
echo ""

echo -e "${YELLOW}2. Navigation from Bounty List${NC}"
echo "   [ ] Go to the main bounty feed"
echo "   [ ] Tap on a bounty poster's avatar in the list"
echo "   [ ] Verify navigation to user profile screen"
echo "   [ ] Verify back button returns to feed"
echo ""

echo -e "${YELLOW}3. Profile Display - Other User${NC}"
echo "   [ ] Profile avatar is displayed correctly"
echo "   [ ] Username and name are shown"
echo "   [ ] Verification badge appears (if verified)"
echo "   [ ] Statistics are displayed (jobs, bounties, badges)"
echo "   [ ] Send Message button is visible"
echo "   [ ] Follow/Unfollow button is visible (if feature enabled)"
echo "   [ ] Three-dot menu is visible in header"
echo "   [ ] Follower/Following counts are shown (if feature enabled)"
echo "   [ ] Skillsets section displays correctly"
echo "   [ ] Portfolio section displays correctly"
echo "   [ ] Achievements section displays correctly"
echo ""

echo -e "${YELLOW}4. Profile Display - Own Profile${NC}"
echo "   [ ] Navigate to your own profile"
echo "   [ ] Edit Profile button is visible"
echo "   [ ] Send Message button is NOT visible"
echo "   [ ] Follow button is NOT visible"
echo "   [ ] Three-dot menu is NOT visible"
echo "   [ ] All sections display correctly"
echo ""

echo -e "${YELLOW}5. Send Message Functionality${NC}"
echo "   [ ] Tap Send Message button on another user's profile"
echo "   [ ] Loading indicator appears"
echo "   [ ] Successfully navigates to messenger"
echo "   [ ] Conversation with user is created/opened"
echo "   [ ] Can send a test message"
echo ""

echo -e "${YELLOW}6. Follow/Unfollow Functionality${NC}"
echo "   [ ] Tap Follow button on another user's profile"
echo "   [ ] Loading indicator appears"
echo "   [ ] Button changes to 'Following'"
echo "   [ ] Follower count increments by 1"
echo "   [ ] Tap Following button to unfollow"
echo "   [ ] Button changes back to 'Follow'"
echo "   [ ] Follower count decrements by 1"
echo ""

echo -e "${YELLOW}7. More Menu - Share${NC}"
echo "   [ ] Tap three-dot menu on another user's profile"
echo "   [ ] Menu dropdown appears"
echo "   [ ] Tap 'Share Profile'"
echo "   [ ] Native share sheet opens"
echo "   [ ] Share contains user profile link"
echo "   [ ] Can share via any available app"
echo ""

echo -e "${YELLOW}8. More Menu - Report${NC}"
echo "   [ ] Tap three-dot menu"
echo "   [ ] Tap 'Report'"
echo "   [ ] Alert appears with reason options"
echo "   [ ] Select 'Spam' option"
echo "   [ ] Success message appears"
echo "   [ ] Menu closes"
echo ""

echo -e "${YELLOW}9. More Menu - Block${NC}"
echo "   [ ] Tap three-dot menu"
echo "   [ ] Tap 'Block'"
echo "   [ ] Confirmation alert appears"
echo "   [ ] Tap 'Block' to confirm"
echo "   [ ] Success message appears"
echo "   [ ] Menu closes"
echo ""

echo -e "${YELLOW}10. Error Handling${NC}"
echo "   [ ] Navigate to non-existent user: /profile/fake-user-id"
echo "   [ ] Error screen displays with message"
echo "   [ ] 'Go Back' button works"
echo "   [ ] Enable airplane mode"
echo "   [ ] Try to load profile"
echo "   [ ] Error banner displays"
echo "   [ ] Can dismiss error banner"
echo ""

echo -e "${YELLOW}11. Responsive Design${NC}"
echo "   [ ] All content fits within screen bounds"
echo "   [ ] No content hidden behind bottom navigation"
echo "   [ ] Safe area respected on iOS (notch area)"
echo "   [ ] Scrolling works smoothly"
echo "   [ ] All buttons are easily tappable"
echo "   [ ] Text is readable on all screen sizes"
echo ""

echo -e "${YELLOW}12. Theme Consistency${NC}"
echo "   [ ] Background is emerald-600 (#059669)"
echo "   [ ] Header matches main app header"
echo "   [ ] Buttons use emerald-200 (#a7f3d0)"
echo "   [ ] Text is white/emerald shades"
echo "   [ ] Consistent with rest of app theme"
echo ""

echo -e "${YELLOW}13. Edge Cases${NC}"
echo "   [ ] Try to message yourself (should show error)"
echo "   [ ] Profile with no portfolio items"
echo "   [ ] Profile with no achievements"
echo "   [ ] Profile with no skillsets"
echo "   [ ] Very long username displays correctly"
echo "   [ ] Very long bio text wraps properly"
echo ""

echo -e "${YELLOW}14. Accessibility${NC}"
echo "   [ ] Enable VoiceOver/TalkBack"
echo "   [ ] All buttons are announced correctly"
echo "   [ ] Navigation is logical with screen reader"
echo "   [ ] All images have alt text"
echo "   [ ] Touch targets are adequate (44x44)"
echo ""

echo -e "${YELLOW}15. Performance${NC}"
echo "   [ ] Profile loads within 2 seconds"
echo "   [ ] No visible lag when scrolling"
echo "   [ ] Images load progressively"
echo "   [ ] No memory warnings in console"
echo "   [ ] Smooth animations/transitions"
echo ""

echo ""
echo -e "${GREEN}✅ Testing Complete!${NC}"
echo ""
echo "If any test fails, please note:"
echo "  • What was expected"
echo "  • What actually happened"
echo "  • Steps to reproduce"
echo "  • Device/simulator info"
echo "  • Screenshots if applicable"
echo ""
echo "=================================================="
echo "  Testing checklist for developers"
echo "=================================================="
